Portafolio1/blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns= [
    path('', render_posts, name='posts'), 
    path('<int:post_id>', post_detail, name="post_detail"),
]

Portafolio1/django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portafolio1/blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    tittle = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

Portafolio1/portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)
    

Portafolio1/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request,'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request,'post_detail.html', {"post": post})

Portafolio1/portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

Portafolio1/blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{post.tittle}}</h2>
<h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

<img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">

<div class="my-4">
    <p>{{post.description|safe}}</p>
</div>

</div>

{% endblock %}

Portafolio1/blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1>Posts</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
    
            <div class="col-9">
              <h2>{{post.tittle}}</h2>
              <p>{{post.description|striptags|truncatechars:100 }}</p>
              <p>{{post.date|date:'M d Y'|upper}}</p>
        
     
              <a href="{% url 'blog:post_detail' post.id %}">{{post.tittle}}</a>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

Portafolio1/portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<!-- Hero Section -->
<header class="row bg-black">
  <div class="col-md-4">
    <img src="{% static 'portfolio/profile1.jpg' %}" />
  </div>

  <div class="col-md-8 my-auto p-4">
    <h1>Soy <strong>Piero Tandaypan</strong></h1>
    <h3>Soy un estudiante de ingenieria en informatica en la universidad arturo pratt</h3>
    <p>Este proyecto es creado en django-python el cual consta en un portafolio que almacene tus proyectos 
      y no solo eso tambien podras crear diferentes tipos de post con el material que tu desees como informacion del pais
      informacion de tu universidad , informacion de videojuegos etc.</p>

    <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/cv1.pdf' %}">Descargar CV</a>
  </div>
</header>

<!-- Porfolio Section -->
<div class="row my-4 text-center">

  <h3>Mis Proyectos</h3>
  <p>Proyectos universitarios: </p>

  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <img src="{{project.image.url }}" class="card-img-top" />

      <div class="card-body">

        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>

        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">Visite el
          Proyecto</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}

  <script type="text/javascript">
    (function(d, m){
        var kommunicateSettings = 
            {"appId":"1886727f94d20a11f8b8e8b1d4b8851bb","popupWidget":true,"automaticChatOpenOnNavigation":true};
        var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
        s.src = "https://widget.kommunicate.io/v2/kommunicate.app";
        var h = document.getElementsByTagName("head")[0]; h.appendChild(s);
        window.kommunicate = m; m._globals = kommunicateSettings;
    })(document, window.kommunicate || {});
/* NOTE : Use web server to view HTML files as real-time update will not work if you directly open the HTML file in the browser. */
</script>

</div>


{% endblock %}

Portafolio1/portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Porfolio</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="text-light">

  {% include 'partials/navbar.html' %}

  <div class="container p-4">
    {% block content %}
    {% endblock %}
  </div>

</body>

</html>

Portafolio1/portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv1.pdf' %}" target="_blank">Descargar</a>
        </li>
      </ul>
    </div>
  </div>
</nav>